default_context:
  project_name: 'async-fastapi'
  project_slug: 'async-fastapi'
  domain_main: 'async-fastapi.com'
  domain_staging: 'stag.async-fastapi.com'
  docker_swarm_stack_name_main: 'async-fastapi-com'
  docker_swarm_stack_name_staging: 'stag-async-fastapi-com'
  secret_key: 'd825147662f255f7bef56a4685b26348bd85530874c2b47d076bc5b2ab0ecd7a'
  first_superuser: 'admin@async-fastapi.com'
  first_superuser_password: 'async-fastapi1!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.async-fastapi.com", "https://stag.async-fastapi.com", "https://async-fastapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@async-fastapi.com'
  postgres_password: 'async-fastapi2!'
  pgadmin_default_user: 'admin@async-fastapi.com'
  pgadmin_default_user_password: 'async-fastapi1!'
  traefik_constraint_tag: 'async-fastapi.com'
  traefik_constraint_tag_staging: 'stag.async-fastapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:asyncfastapi1!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
