default_context:
  project_name: 'johnson-website'
  project_slug: 'johnson-website'
  domain_main: 'johnson-website.com'
  domain_staging: 'stag.johnson-website.com'
  docker_swarm_stack_name_main: 'johnson-website-com'
  docker_swarm_stack_name_staging: 'stag-johnson-website-com'
  secret_key: 'd825147662f255f7bef56a4685b26348bd85530874c2b47d076bc5b2ab0ecd7a'
  first_superuser: 'admin@johnson-website.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.johnson-website.com", "https://stag.johnson-website.com", "https://johnson-website.com", "http://local.dockertoolbox.johnson-website.com", "http://localhost.johnson-website.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@johnson-website.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@johnson-website.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'johnson-website.com'
  traefik_constraint_tag_staging: 'stag.johnson-website.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
